spring:
  profiles: local
  datasource:
    sql-script-encoding: UTF-8
    initialization-mode: always
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:./data/testdb
      username: sa
      password:
  h2:
    console:
      enabled: true
      path: /h2_console
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format-sql: false
  devtools:
    restart:
      enabled: true

api:
  kakao:
    url: https://dapi.kakao.com
    key: a18861c2d472d200381663d7239b9c7b

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: 8098