spring:
  profiles: local
  datasource:
    sql-script-encoding: UTF-8
    initialization-mode: always
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:./data/testdb
      username: sa
      password:
  h2:
    console:
      enabled: true
      path: /h2_console
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format-sql: false
    open-in-view: false
  devtools:
    restart:
      enabled: true

hystrix:
  command:
    productInfo:   # command key. use 'default' for global setting.
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000     # 2sec. / default 1sec.
      metrics:
        rollingStats:
          timeInMilliseconds: 10000         # 10sec. / default 10sec.
      circuitBreaker:
        requestVolumeThreshold: 5           # Minimum number of request to calculate circuit breaker's health. default 20
        errorThresholdPercentage: 50        # Error percentage to open circuit. default 50
        sleepWindowInMilliseconds: 10000    # 10sec. / default 5sec.
app:
  jwt:
    token-key: seran.token.key
    expires-limit: 1800000        # 30 min.
  api:
    kakao:
      url: https://dapi.kakao.com
      key: f12b3cac1ec91947b79fe537730e4c21
    naver:
      url: https://openapi.naver.com
      client-id: gmaJIm_hIoSLCLyAvzdp
      client-secret: XQ7LKJrcR0

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

