spring:
  datasource:
    sql-script-encoding: UTF-8
    url: jdbc:h2:~/project
    data-username: sa
    data-password:
    initialization-mode: always
  h2:
    console:
      enabled: true
      path: /h2_console
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format-sql: false
  devtools:
    restart:
      enabled: true

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: 8098